pipeline:
  name: python_hello_world
  identifier: python_hello_world
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Connector
        repoName: python-hello-world
        build: <+input>
  stages:
    - stage:
        name: build_app
        identifier: build_app
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Kubernetes_Cluster_Connector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: test_app
                      identifier: test_app
                      spec:
                        connectorRef: Docker_Hub_Connector
                        image: python:3-alpine
                        shell: Sh
                        command: |-
                          pip install -r requirements.txt
                          python -m unittest discover
                  - step:
                      type: Sonarqube
                      name: sonarqube_scan
                      identifier: sonarqube_scan
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                        auth:
                          access_token: <+secrets.getValue("SonarQube_Token")>
                          domain: https://sonarcloud.io
                          ssl: true
                        settings:
                          product_organization_id: opeomotayo
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build_and_push_to_dockerhub
                  identifier: build_and_push_to_dockerhub
                  spec:
                    connectorRef: Docker_Hub_Connector
                    repo: opeomotayo/python-hello-world
                    tags:
                      - <+pipeline.sequenceId>
    - stage:
        name: deploy_to_preprod
        identifier: deploy_to_preprod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: python_hello_world_preprod
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: preprod_environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: preprod_infrastructure
          execution:
            steps:
              - step:
                  name: rollout_deployment
                  identifier: rollout_deployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: rollback_rollout_deployment
                  identifier: rollback_rollout_deployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: prod_approval
        identifier: prod_approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: harness_approval
                  identifier: harness_approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - DevOps_Team
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: deploy_to_prod
        identifier: deploy_to_prod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: python_hello_world_prod
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: prod_environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prod_infrastructure
          execution:
            steps:
              - step:
                  name: rollout_deployment
                  identifier: rollout_deployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rrollback_rollout_deployment
                  identifier: rollback_rollout_deployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback